setting for development environment
CodeSoom/project-react-1-iamhwang pull request #1
Opened 2020-07-29 16:11 UTC by iamhwang

Installs needed modules for development.

Sets up config files for webpack, babel, jest.

Tests for Redux toolkit working.

2020-07-30 12:47 UTC, wholemann requested changes
.gitignore 설정을 빼먹지 말아주세요.

node_modules 는 commit 되어선 안 됩니다.

2020-07-31 09:30 UTC, iamhwang reviewed
Sets `.gitignore` and removes `.vscode`, `node_modules` files

2020-07-31 09:49 UTC, iamhwang commented on src/HomePage.jsx
> +  );
초기화면을 보여주는 HomePage 컴포넌트를 상태관리 컴포넌트로 하고, 
화면을 그리는  컴포넌트를 그려지는 위치에 따라 3등분했다.(Top, Center, Bottom) 
이렇게 나누는게 의미가 있나? 
차라리 하나의 그림 컴포넌트에서 `<div>` 태그로 그려지는 위치를 구분주는게 좋지 않을까?

2020-07-31 10:30 UTC, merged

2020-07-31 13:30 UTC, hannut91 commented on src/HomePage.jsx
> +  );
단순하게 위 중간 아래는 좀 아쉽네요 ㅎㅎ 기능 혹은 역할에 따라 나눠주는게 좋을 것 같아요